- name: Include service manager specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "service_mgr_{{ ansible_service_mgr | mandatory }}.yml"
    - service_mgr_default.yml

- include_tasks: start_aem.yml
  when: aem_service_state == 'started'

- include_tasks: stop_aem.yml
  when: aem_service_state == 'stopped'

- include_tasks: restart_aem.yml
  when: aem_service_state == 'restarted'
