- include_tasks: start_aem.yml
  when: aem_service_state == 'started'

- include_tasks: stop_aem.yml
  when: aem_service_state == 'stopped'

- include_tasks: restart_aem.yml
  when: aem_service_state == 'restarted'
