- include: start_aem.yml
  when: aem_service_state == 'started'

- include: stop_aem.yml
  when: aem_service_state == 'stopped'

- include: restart_aem.yml
  when: aem_service_state == 'restarted'