- name: Start AEM.
  service:
    name: "{{ aem_instance_name }}"
    state: started

- name: Wait for AEM startup.
  uri:
    url: "http://localhost:{{ aem_port }}/libs/granite/core/content/login.html"
    return_content: yes
  register: result
  until: result.content.find("Welcome to Adobe Experience Manager") != -1
  retries: "{{ aem_service_timeout // 10 }}"
  delay: 10