- name: Start AEM.
  service:
    name: "{{ aem_service_name }}"
    state: started

- name: "Wait for AEM startup. [{{ inventory_hostname }}]"
  uri:
    url: "{{ aem_service_login_url }}"
    return_content: yes
  register: result
  until: result.content.find("QUICKSTART_HOMEPAGE") != -1
  retries: "{{ aem_service_timeout // 10 }}"
  delay: 10