- name: Start AEM (escalated).
  service:
    name: "{{ aem_service_name }}"
    state: started
  register: aem_service_start_result_escalated
  when: not aem_service_restricted_mode

- name: Start AEM (restricted).
  block:
    - name: Retrieve AEM status (restricted).
      raw: "{{ _aem_service_status_command }}"
      changed_when: false
      register: _aem_status_result_1
      failed_when:
        - _aem_status_result_1.rc != 0
        - _aem_status_result_1.rc != 4

    - name: Start AEM (restricted).
      raw: "{{ _aem_service_start_command }}"
      when: _aem_status_result_1.rc != 0
      register: aem_service_start_result_restricted

  when: aem_service_restricted_mode

- name: "Wait for AEM startup. [{{ inventory_hostname }}]"
  uri:
    url: "{{ aem_service_login_url }}"
    return_content: yes
  register: result
  until: result.content.find("QUICKSTART_HOMEPAGE") != -1
  retries: "{{ aem_service_timeout // 10 }}"
  delay: 10
  when: aem_service_start_result_escalated.changed or aem_service_start_result_restricted.changed

  tags:
    - skip_ansible_lint