- name: Stop AEM.
  service:
    name: "{{ aem_service_name }}"
    state: stopped
  when: aem_service_raw_cmd_start is undefined
  register: aem_service_stop_result

- name: Stop AEM (with raw command line).
  command: "{{ aem_service_raw_cmd_stop }}"
  when: aem_service_raw_cmd_start is defined
  register: aem_service_stop_result
