- name: Stop AEM.
  service:
    name: "{{ aem_service_name }}"
    state: stopped

- name: Wait for AEM shutdown.
  wait_for:
    port: "{{ aem_service_port }}"
    state: stopped
    delay: 10
    timeout: "{{ aem_service_timeout }}"